### ISSUE TITLE
Remove the friggin' demos entirely or at least mostly

### ISSUE THREAD

**Issue by bitprophet** [paramiko/paramiko#1245]
## Background

- The demos, generally, generate a disproportionate amount of support burden, in multiple "why doesn't this copypasta work?" and "hey the demo is actually broken in XYZ ways" flavors.
- Furthermore, a large proportion of them really boil down (to me) as "ugh why aren't you just using Fabric (2) for this, it's basically the real world reference implementation".

## TODO

- [ ] Identify exactly which demos are covered by Fabric, which aren't but should/can be, and which are truly extra use cases that don't deserve their own high level implementation
- [ ] If that leaves us with no demos, great, remove the entire folder, and make sure we link to Fabric 2 explicitly in the README and docs.
- [ ] Otherwise:
  - [ ] Remove the first category entirely, and put a README in the demos folder repeating the plea to use Fabric 2.
  - [ ] If there are any in the 2nd category, make Fabric tickets for 'em, and remove 'em.
  - [ ] If there's anything left in the 3rd category for some reason, leave them as-is.

**Comment by bitprophet** [comment]
Another minor issue from abovelinked ticket: folks who do want to copy/paste/modify the demos also run into LGPL drive licensing confusion. Presumably not the case if they were to import and call unmodified Fabric 2 code. (Well, but also because Fabric is, based on "just importing LGPL does not make you subject to LGPL", actually BSD licensed.)

**Comment by remram44** [comment]
Wondering about this. Are there examples somewhere I can actually read and use? LGPL is highly restrictive.
