### ISSUE TITLE
[CVE PENDING] Server-side auth vulnerability [DESC TK]

### ISSUE THREAD

**Issue by bitprophet** [paramiko/paramiko#1283]
## Background

Security vulnerability on Paramiko's server side (**NOT** client side), as reported by Daniel Hoffman of [usd AG](https://www.usd.de/en/).

I was emailed by the above on 2018.08.31 and (due to being on vacation at the time) was able to review the initial information on today's date (2018.09.06). Daniel submitted the following:

- sample vanilla-enough server-side code loop (using standard/public API members with no additions besides logging and specification of expected auth mechanisms)
- sample client-side code which exploits the vulnerability in the server (TK)
- detailed explanation of why the exploit works, with references to parts of Paramiko's server-side code
- recommended fix

At time of writing, I have done a cursory read of the code snippets & explanation, and confirmed that the sample code does appear to exhibit the described exploit.

## Actual, post-fix description

The crux of it is as follows:

- The exploit is that malicious clients can trick the Paramiko server into thinking the client is authenticated, without providing any authentication. Yup. That's bad. Real bad.
- The flaw is in the `Transport` class, which is (regrettably IMHO; it's not my design) used unadulterated for both client and server use cases. No subclassing or anything; only a few very minor branch points.
- It, and its symbiont class `AuthHandler`, both maintain a few "handler tables" for dispatching on message types within the main event loop; e.g. see `MSG_USERAUTH_REQUEST`, dispatch to an auth request handler method.
- Smart users will already have put the previous facts together to figure out that...the exploit is the client sending `MSG_USERAUTH_SUCCESS` to the server. This is normally a server-to-client only message!
  - The Paramiko server then handles this message using a handler (within `AuthHandler`) _intended_ for use by _client use cases_, because there is no differentiation in play.
  - And because the code is so strongly shared, this ends up flipping a flag saying "the other end is authenticated", which the server code continues to reference to determine if the client passed auth.
- Thus, a malicious client can simply send that bogus message to set itself as authenticated for the rest of the session. Open, sesame.
- The fix has been to separate the handler tables into specific client vs server components (given that, at least for the AuthHandler where this all takes place, there are no bidirectionally useful message types) and serve up only one or the other during dispatch, never both.
  - This was done in a backwards compatible manner, replacing static dicts with a dict-returning `@property`.
- Due to expediency, I have not yet expanded this fix to the other couple of tables involved, but my guess is that the AuthHandler's table was the one that needed it most; past the auth step, any incorrect messages should just result in errors from the server and not exploitable server state.
- The fix has been backported to Paramiko 2.0 and up.

## TODO

- [x] take up Daniel on his offer to create a CVE; less work for me, but also, a security company has more experience with that process than I do, namely "any at all"
- [x] double check the details of the vulnerability so that I understand it more deeply
- [x] consider whether the suggested fix is valid (it has to do with Paramiko's reuse of code across client/server use cases)
- [ ] ~confirm exploit & fix are both valid to 1.17.x/1.18.x (at present I am still considering 1.17.x to be pseudo-LTS and getting bugfixes, though this will soon cease) and up~ _- nope, 2.0 and up, sorry folks. it's gotta happen sometime_
- [x] test, patch, confirm
- [x] changelog entry
  - **NOTE:** may want to wait for CVE filing if not done yet, so at least this one commit has the CVE number in it? also consider a rebase to add it to the main patch commit/s
- [x] merge up to all branches
- [ ] push & release at once so fix is live
- [ ] update this ticket with my notes/real description
- [ ] send a security notice out via Tidelift as well as Twitter

**Comment by bitprophet** [comment]
The reporter initiated the CVE generation process, but it's been a few days with no movement on the part of the CVE creating authority & they've got a visible backlog as well. I'm probably going to release this patch, update this ticket with the details, and then just update the changelog & ticket once the CVE is actually assigned, for documentation reasons.

Doesn't seem worthwhile to delay patch release just so we can bake it in, if it's going to take this long. We'll see, maybe I'll get lucky and the time it takes me to do the rest of my release cycle will give them enough of a window 😝

**Comment by bitprophet** [comment]
Kicking around the idea of using this as the place to say "1.x is dead". If not now, when? I just put in the work in #1291 to make it even easier to forward port 2.0.x up to master, but extending that to 1.17/1.18 is an even bigger kettle of fish, and the problems with 1.18 adding features not present in 2.0/2.1 (preventing a straight merge-up) will never go away.

**Comment by bitprophet** [comment]
Unrelated: still no movement on the CVE-tracking spreadsheet I was linked to. I didn't actually get all the way to merging this today (though I did make progress) so we'll see if it pops up before I finish/merge...

**Comment by bitprophet** [comment]
Took longer to identify a good way to really test this, than anticipated, thanks to the codebase being emphatically not designed with testing in mind 😭 

On the plus side I identified a strongly related pseudo-bug which has been fixed (doubt it affects anyone who isn't running Paramiko on both ends of a conversation, but...). Two threads yelling "`MSG_UNIMPLEMENTED`!" at each other until one of them shuts down 😂

**Comment by bitprophet** [comment]
Updated desc with details. waiting for Travis to be all green before I release...though they seem to be having a bad day.

**Comment by bitprophet** [comment]
2.0.9 et al are on PyPI 🎉

**Comment by hsoft** [comment]
Considering that it's the second important security problem in a short time frame and that the exploit seems relatively easy to find, can't we anticiptate many other problems of this kind to pop up?

Considering that the server feature of paramiko is probably seldom used, couldn't we entertain the idea of stripping paramiko of its server functionality to avoid all this pain?

**Comment by hsoft** [comment]
Or, maybe, disable it unless an environment variable of the `I_KNOW_WHAT_IM_DOING` kind is set, and backport the de-activation in all previous branches (including 1.x) so you can finally close the books on those branches without feeling the guilt of leaving potential users at risk.

**Comment by attritionorg** [comment]
CVE-2018-1000805
